version: '3.8'

services:
  api:
    image: my-golang-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:mypassword@db:5432/gses?sslmode=disable"
      APP_CURRENCY_EXCHANGE_URL: "https://api.apilayer.com/exchangerates_data/latest"
      APP_CURRENCY_EXCHANGE_KEY: "EPPBjcIYnYl0rToRCEWpzFm3S8JYWCRq"
      MAILPASS: "ikreezqkkhflijn"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
