version: 1
threshold:
  compliance: 100
  coverage: 90
dependenciesRules:
  - package: "api"
    shouldOnlyDependsOn:
      internal:
        - "domains"
        - "utils"
        - "repo"
  - package: "constants"
    shouldOnlyDependsOn:
      internal:
        - "domains"
        - "utils"
  - package: "docs"
    shouldOnlyDependsOn:
      internal:
        - "domains"
  - package: "domains/cron-jobs"
    shouldOnlyDependsOn:
      internal:
        - "domains"
        - "utils"
        - "domains/mails"
        - "domains/rates"
        - "domains/subscribers"
  - package: "domains/mails"
    shouldOnlyDependsOn:
      internal:
        - "domains"
        - "utils"
  - package: "domains/rates"
    shouldOnlyDependsOn:
      internal:
        - "domains"
        - "utils"
  - package: "domains/subscribers"
    shouldOnlyDependsOn:
      internal:
        - "domains"
        - "utils"
        - "constants"
  - package: "domains"
    shouldNotDependsOn:
      internal:
        - "api"
  - package: "repo"
    shouldOnlyDependsOn:
      internal:
        - "utils"
  - package: "utils"
    shouldNotDependsOn:
      internal:
        - "api"
        - "domains"
