name: lint

on:
  push:
    branches:
      - '*'
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  golang-lint:
    name: gosec
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: go work init and download
        run: |
          echo 'go 1.22.4' > go.work
          echo 'use .' >> go.work
          echo 'use ./email_sender' >> go.work
          go mod tidy
          go mod download

      - name: run golangci-lint
        run: golangci-lint run

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: go work init and download
        run: |
          echo 'go 1.22.4' > go.work
          echo 'use .' >> go.work
          echo 'use ./email_sender' >> go.work
          go mod tidy
          go mod download

      - name: run gosec
        run: "`go env GOPATH`/bin/gosec ./..."

      - name: install arch-go
        run: go install github.com/fdaines/arch-go@latest

      - name: go work init and download
        run: |
          echo 'go 1.22.4' > go.work
          echo 'use .' >> go.work
          echo 'use ./email_sender' >> go.work
          go mod tidy
          go mod download

      - name: run arch-go
        run: arch-go
