name: lint

on:
  push:
    branches:
      - '*'
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  golang-lint:
    name: gosec
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: install arch-go
        run: go install github.com/fdaines/arch-go@latest

      - name: go mod tidy and download for all projects
        run: |
          go mod tidy
          go mod download
          cd email_sender
          go mod tidy
          go mod download
          cd ..

      - name: set GOPATH for email_sender
        run: echo "GOPATH=$(go env GOPATH):$(pwd)/email_sender" >> $GITHUB_ENV

      - name: run golangci-lint for main project
        run: golangci-lint run ./...

      - name: run golangci-lint for email_sender
        run: cd email_sender && golangci-lint run ./...

      - name: run gosec for main project
        run: "`go env GOPATH`/bin/gosec ./..."

      - name: run gosec for email_sender
        run: cd email_sender && "`go env GOPATH`/bin/gosec ./..."

      - name: run arch-go
        run: arch-go
