name: unit-tests

on:
  push:
    branches:
      - '*'
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.4

    - name: install dependencies
      run: go mod download

    - name: rates tests
      run: go test -v ./internal/rates

    - name: subscribers tests
      run: go test -v ./internal/subscribers
